#!/usr/bin/env python3
"""Generate public taxonomy and relationship exploration pages from TIG semantic sources."""
from __future__ import annotations

import re
from collections import Counter, defaultdict
from pathlib import Path

from semantic_model_core import ROOT, build_semantic_model, load_concepts

EXPLORE_DIR = ROOT / "explore"


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9]+", "-", value)
    return value.strip("-") or "term"


def concept_labels() -> dict[str, str]:
    concepts, _ = load_concepts()
    return {
        concept_id: str(data.get("term") or concept_id.rsplit(":", 1)[-1]).strip()
        for concept_id, data in concepts.items()
    }


def concept_link(concept_id: str, labels: dict[str, str]) -> str:
    label = labels.get(concept_id, concept_id)
    slug = slugify(label)
    return f"[{label}]({{{{ '/terms/{slug}/' | relative_url }}}})"


def write_taxonomy(graph: dict, labels: dict[str, str]) -> None:
    taxonomy = graph["taxonomy"]
    hierarchy = taxonomy.get("hierarchy") or []
    by_parent: dict[str, list[str]] = defaultdict(list)
    for edge in hierarchy:
        by_parent[edge["parent"]].append(edge["child"])

    lines = [
        "---",
        'title: "Taxonomy"',
        'parent: "Explore Concepts"',
        "nav_order: 3",
        "permalink: /explore/taxonomy/",
        "---",
        "",
        "# TIG Taxonomy",
        "",
        "This view is generated from the governed TIG semantic model. It is a navigation projection over canonical concepts, not an independent semantic authority surface.",
        "",
        f"- Canonical concepts: **{taxonomy.get('concept_count', 0)}**",
        f"- Taxonomy roots: **{len(taxonomy.get('roots') or [])}**",
        f"- Governed hierarchy edges: **{len(hierarchy)}**",
        "",
        "## Reviewed hierarchy",
        "",
    ]

    if not hierarchy:
        lines.append("No governed broader/narrower hierarchy has been published yet.")
    else:
        for parent in sorted(by_parent, key=lambda item: labels.get(item, item).lower()):
            lines.append(f"### {concept_link(parent, labels)}")
            lines.append("")
            for child in sorted(by_parent[parent], key=lambda item: labels.get(item, item).lower()):
                lines.append(f"- {concept_link(child, labels)}")
            lines.append("")

    lines.extend([
        "## Featured roots",
        "",
        "Featured roots are navigation anchors declared by the semantic model. A concept can be a taxonomy root without being featured.",
        "",
    ])
    for concept_id in taxonomy.get("featured_roots") or []:
        lines.append(f"- {concept_link(concept_id, labels)}")

    lines.extend([
        "",
        "## Machine-readable view",
        "",
        "Use `generated/json/tig-taxonomy.json` for deterministic machine consumption.",
        "",
        "[Read the taxonomy model]({{ '/semantic-model/taxonomy/' | relative_url }}) · [View semantic products]({{ '/artifacts/' | relative_url }})",
        "",
        "---",
        "",
        "*Generated by `tools/build_site_information_architecture.py` from governed TIG semantic sources.*",
        "",
    ])
    (EXPLORE_DIR / "taxonomy.md").write_text("\n".join(lines), encoding="utf-8")


def write_relationships(graph: dict, labels: dict[str, str]) -> None:
    ontology = graph["ontology"]
    edges = ontology.get("edges") or []
    predicate_counts = Counter(edge["predicate"] for edge in edges)
    degree = Counter()
    adjacency: dict[str, Counter[str]] = defaultdict(Counter)
    for edge in edges:
        degree[edge["subject"]] += 1
        degree[edge["object"]] += 1
        adjacency[edge["subject"]][edge["predicate"]] += 1

    lines = [
        "---",
        'title: "Relationships"',
        'parent: "Explore Concepts"',
        "nav_order: 4",
        "permalink: /explore/relationships/",
        "---",
        "",
        "# Semantic Relationships",
        "",
        "This view is generated from TIG's projectable ontology edges. Every edge has resolvable canonical concept endpoints and provenance; unresolved inherited references remain explicit evidence but are not emitted as typed graph edges.",
        "",
        f"- Typed ontology edges: **{ontology.get('edge_count', len(edges))}**",
        f"- Excluded unresolved inherited references: **{ontology.get('excluded_unresolved_reference_count', 0)}**",
        "",
        "## Predicate surface",
        "",
        "| Predicate | Edges | Meaning in this view |",
        "|---|---:|---|",
        f"| `broader` | {predicate_counts.get('broader', 0)} | Subject is classified under the object |",
        f"| `narrower` | {predicate_counts.get('narrower', 0)} | Subject classifies the object more narrowly |",
        f"| `related` | {predicate_counts.get('related', 0)} | Concepts are semantically related without a hierarchy claim |",
        "",
        "## Highly connected concepts",
        "",
        "These are navigation aids ranked by graph degree, not importance scores or authority rankings.",
        "",
        "| Concept | Connected edges | Outgoing relation mix |",
        "|---|---:|---|",
    ]

    for concept_id, count in sorted(
        degree.items(), key=lambda item: (-item[1], labels.get(item[0], item[0]).lower())
    )[:30]:
        mix = ", ".join(
            f"`{predicate}` {value}" for predicate, value in sorted(adjacency.get(concept_id, {}).items())
        ) or "—"
        lines.append(f"| {concept_link(concept_id, labels)} | {count} | {mix} |")

    lines.extend([
        "",
        "## Authority boundary",
        "",
        "Graph connectivity is descriptive. It does not create normative authority, assurance level, implementation priority or certification status.",
        "",
        "[Read the ontology model]({{ '/semantic-model/ontology/' | relative_url }}) · [Read provenance & authority]({{ '/semantic-model/provenance/' | relative_url }})",
        "",
        "---",
        "",
        "*Generated by `tools/build_site_information_architecture.py` from governed TIG semantic sources.*",
        "",
    ])
    (EXPLORE_DIR / "relationships.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    EXPLORE_DIR.mkdir(parents=True, exist_ok=True)
    graph = build_semantic_model()
    labels = concept_labels()
    write_taxonomy(graph, labels)
    write_relationships(graph, labels)
    print(
        "Generated site semantic exploration: "
        f"{len(graph['taxonomy'].get('hierarchy') or [])} hierarchy edges, "
        f"{graph['ontology'].get('edge_count', 0)} ontology edges"
    )


if __name__ == "__main__":
    main()
