#!/usr/bin/env python3
"""Validate TIG public information architecture and internal navigation targets."""
from __future__ import annotations

import re
import sys
from pathlib import Path

import yaml

from semantic_model_core import ROOT

MANAGED_PAGES = [
    ROOT / "index.md",
    ROOT / "explore" / "index.md",
    ROOT / "explore" / "taxonomy.md",
    ROOT / "explore" / "relationships.md",
    ROOT / "concepts.md",
    ROOT / "use" / "index.md",
    ROOT / "artifacts.md",
    ROOT / "semantic-model" / "index.md",
    ROOT / "semantic-model" / "vocabulary.md",
    ROOT / "semantic-model" / "taxonomy.md",
    ROOT / "semantic-model" / "ontology.md",
    ROOT / "semantic-model" / "provenance.md",
    ROOT / "governance" / "index.md",
    ROOT / "project" / "index.md",
]

RELATIVE_URL_RE = re.compile(r"\{\{\s*['\"](?P<route>/[^'\"]+)['\"]\s*\|\s*relative_url\s*\}\}")
FRONT_MATTER_RE = re.compile(r"\A---\n(?P<front>.*?)\n---\n", re.DOTALL)


def normalize_route(route: str) -> str:
    if not route.startswith("/"):
        route = "/" + route
    if route != "/" and not route.endswith("/"):
        route += "/"
    return route


def front_matter(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    match = FRONT_MATTER_RE.match(text)
    if not match:
        return {}
    value = yaml.safe_load(match.group("front")) or {}
    return value if isinstance(value, dict) else {}


def route_index() -> set[str]:
    routes: set[str] = {"/"}
    for path in ROOT.rglob("*.md"):
        if any(part in {".git", "node_modules", "vendor", "_site"} for part in path.parts):
            continue
        rel = path.relative_to(ROOT)
        fm = front_matter(path)
        permalink = fm.get("permalink")
        if isinstance(permalink, str) and permalink.startswith("/"):
            routes.add(normalize_route(permalink))

        if rel.parts and rel.parts[0] == "_terms":
            routes.add(normalize_route(f"/terms/{path.stem}/"))
            continue

        if path.name == "index.md":
            parent = rel.parent.as_posix()
            routes.add(normalize_route("/" if parent == "." else f"/{parent}/"))
        else:
            routes.add(normalize_route(f"/{rel.with_suffix('').as_posix()}/"))

    return routes


def validate_required_pages(errors: list[str]) -> None:
    for path in MANAGED_PAGES:
        if not path.exists():
            errors.append(f"required IA page missing: {path.relative_to(ROOT)}")


def validate_generated_views(errors: list[str]) -> None:
    for name in ["taxonomy.md", "relationships.md"]:
        path = ROOT / "explore" / name
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        marker = "Generated by `tools/build_site_information_architecture.py`"
        if marker not in text:
            errors.append(f"generated exploration page lacks generator marker: explore/{name}")


def validate_navigation(errors: list[str]) -> None:
    top_level = [
        ROOT / "explore" / "index.md",
        ROOT / "semantic-model" / "index.md",
        ROOT / "use" / "index.md",
        ROOT / "governance" / "index.md",
        ROOT / "project" / "index.md",
    ]
    orders: dict[int, str] = {}
    for path in top_level:
        if not path.exists():
            continue
        fm = front_matter(path)
        order = fm.get("nav_order")
        if not isinstance(order, int):
            errors.append(f"top-level navigation page lacks integer nav_order: {path.relative_to(ROOT)}")
            continue
        if order in orders:
            errors.append(
                f"duplicate top-level nav_order {order}: {orders[order]} and {path.relative_to(ROOT)}"
            )
        orders[order] = path.relative_to(ROOT).as_posix()

    semantic = front_matter(ROOT / "semantic-model" / "index.md")
    if semantic.get("title") != "Semantic Model":
        errors.append("Semantic Model must remain a first-class top-level navigation section")


def validate_internal_links(errors: list[str]) -> None:
    routes = route_index()
    for path in MANAGED_PAGES:
        if not path.exists():
            continue
        text = path.read_text(encoding="utf-8")
        for match in RELATIVE_URL_RE.finditer(text):
            route = normalize_route(match.group("route"))
            if route not in routes:
                errors.append(f"broken managed-page route {route} in {path.relative_to(ROOT)}")


def validate_authority_boundary(errors: list[str]) -> None:
    prohibited = [
        ROOT / "glossary" / "terms",
        ROOT / "governance" / "semantic-model.yaml",
        ROOT / "governance" / "taxonomy-relations.yaml",
        ROOT / "schemas",
    ]
    for path in prohibited:
        if not path.exists():
            errors.append(f"semantic authority source unexpectedly missing: {path.relative_to(ROOT)}")


def main() -> int:
    errors: list[str] = []
    validate_required_pages(errors)
    validate_generated_views(errors)
    validate_navigation(errors)
    validate_internal_links(errors)
    validate_authority_boundary(errors)

    if errors:
        print("Site information architecture validation FAILED")
        for error in errors:
            print(f"- {error}")
        return 1

    print(f"Site information architecture validation passed: {len(MANAGED_PAGES)} managed pages checked")
    return 0


if __name__ == "__main__":
    sys.exit(main())
